use serde::{Deserialize, Serialize};

use super::RiskLevel;

/// Report generated by impact analysis, describing the risk and scope of a change.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImpactReport {
    pub score: f32,
    pub symbols_affected: usize,
    pub dependent_files: Vec<String>,
    pub contracts_affected: Vec<String>,
    pub risk_level: RiskLevel,
    pub recommendation: String,
}
