#!/usr/bin/env node
/**
 * screenshots.mjs — Convert .ansi files to styled terminal PNGs via Playwright.
 *
 * Pipeline:  .ansi → ansi-to-html → styled HTML → Playwright screenshot → .png
 *
 * Usage:
 *   1. npm install playwright ansi-to-html
 *   2. node scripts/screenshots.mjs
 *
 * Input:  docs/screenshots/*.ansi  (generated by `cargo run --example wizard_screenshots`)
 * Output: docs/screenshots/*.png
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
import Convert from 'ansi-to-html';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const REPO_ROOT = join(__dirname, '..');
const ANSI_DIR = join(REPO_ROOT, 'docs', 'screenshots');
const OUT_DIR = ANSI_DIR;

const convert = new Convert({
  fg: '#c0c0d0',
  bg: '#0a0a14',
  colors: {
    0: '#000000', 1: '#cc3333', 2: '#00cc66', 3: '#cccc33',
    4: '#3366cc', 5: '#cc33cc', 6: '#00cccc', 7: '#e0e0f0',
    8: '#555566', 9: '#ff6666', 10: '#66ff99', 11: '#ffff66',
    12: '#6699ff', 13: '#ff66ff', 14: '#66ffff', 15: '#ffffff',
  },
});

const steps = [
  { file: 'welcome', title: 'Welcome' },
  { file: 'token', title: 'Token Setup' },
  { file: 'server', title: 'Server Config' },
  { file: 'storage', title: 'Storage Config' },
  { file: 'embeddings', title: 'Embeddings Provider' },
  { file: 'review', title: 'Review & Save' },
];

const HTML_TEMPLATE = (title, body) => `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Xavier2 Installer — ${title}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&display=swap');
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      background: #0a0a14;
      display: flex;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
      padding: 40px;
    }
    .terminal {
      font-family: 'JetBrains Mono', 'Cascadia Code', 'Fira Code', 'Consolas', monospace;
      font-size: 14px;
      line-height: 1.4;
      padding: 24px 28px;
      background: #0a0a14;
      border-radius: 10px;
      box-shadow: 0 0 60px rgba(0, 180, 180, 0.12), 0 4px 24px rgba(0, 0, 0, 0.5);
      white-space: pre;
      color: #c0c0d0;
    }
    .terminal .ansi-black-fg { color: #000000; }
    .terminal .ansi-red-fg { color: #cc3333; }
    .terminal .ansi-green-fg { color: #00cc66; }
    .terminal .ansi-yellow-fg { color: #cccc33; }
    .terminal .ansi-blue-fg { color: #3366cc; }
    .terminal .ansi-magenta-fg { color: #cc33cc; }
    .terminal .ansi-cyan-fg { color: #00cccc; }
    .terminal .ansi-white-fg { color: #e0e0f0; }
    .terminal .ansi-bright-black-fg { color: #555566; }
    .terminal .ansi-bright-red-fg { color: #ff6666; }
    .terminal .ansi-bright-green-fg { color: #66ff99; }
    .terminal .ansi-bright-yellow-fg { color: #ffff66; }
    .terminal .ansi-bright-blue-fg { color: #6699ff; }
    .terminal .ansi-bright-magenta-fg { color: #ff66ff; }
    .terminal .ansi-bright-cyan-fg { color: #66ffff; }
    .terminal .ansi-bold { font-weight: bold; }

    /* Override ansi-to-html's default bg to our dark theme */
    .terminal .ansi-bg-black { background-color: #0a0a14; }
  </style>
</head>
<body>
  <pre class="terminal">${body}</pre>
</body>
</html>`;

async function main() {
  mkdirSync(OUT_DIR, { recursive: true });

  console.log('Launching Playwright...');
  const browser = await chromium.launch();
  const context = await browser.newContext({
    viewport: { width: 1280, height: 600 },
    deviceScaleFactor: 2,
  });

  for (const step of steps) {
    const ansiPath = join(ANSI_DIR, `${step.file}.ansi`);
    const pngPath = join(OUT_DIR, `${step.file}.png`);

    console.log(`  Processing: ${step.file} -> ${basename(pngPath)}`);

    let ansiText;
    try {
      ansiText = readFileSync(ansiPath, 'utf-8');
    } catch (e) {
      console.error(`    ⚠ Missing .ansi file: ${ansiPath}`);
      continue;
    }

    const htmlBody = convert.toHtml(ansiText);
    const html = HTML_TEMPLATE(step.title, htmlBody);

    const page = await context.newPage();
    await page.setContent(html, { waitUntil: 'networkidle' });

    // Wait for font to load
    await page.waitForTimeout(500);

    const element = page.locator('.terminal');
    await element.screenshot({ path: pngPath });
    console.log(`    ✓ ${pngPath}`);

    await page.close();
  }

  await browser.close();
  console.log(`Done! ${steps.length} screenshots in ${OUT_DIR}`);
}

main().catch((err) => {
  console.error('Fatal:', err);
  process.exit(1);
});
