# Xavier2 Development Coordinator v2
# Persistent development loop for Xavier2 project
# Agent Directives: Think First, Simplicity, Surgical, Goal-Driven

param(
    [int]$CycleMinutes = 20
)

$XAVIER2_URL = "http://localhost:8006"
$TOKEN = "dev-token"
$REPO = "iberi22/xavier2"
$LOG_DIR = "E:\scripts-python\xavier2\logs"

if (!(Test-Path $LOG_DIR)) { New-Item -ItemType Directory -Path $LOG_DIR -Force | Out-Null }
$LOG_FILE = "$LOG_DIR\dev-coordinator.log"
$PID_FILE = "$LOG_DIR\dev-coordinator.pid"

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "$timestamp [$Level] $Message" | Tee-Object -FilePath $LOG_FILE -Append
}

function Get-GitHubIssues {
    param([int]$Limit = 30)
    try {
        $url = "https://api.github.com/repos/$REPO/issues?state=open&per_page=$Limit&sort=updated"
        $issues = Invoke-RestMethod $url -TimeoutSec 15
        return $issues | Where-Object { $_.pull_request -eq $null }
    } catch {
        Write-Log "GitHub API error: $_" "WARN"
        return @()
    }
}

function Get-GitHubPRs {
    param([int]$Limit = 10)
    try {
        $url = "https://api.github.com/repos/$REPO/pulls?state=open&per_page=$Limit&sort=updated"
        $prs = Invoke-RestMethod $url -TimeoutSec 15
        return $prs
    } catch {
        Write-Log "GitHub PR API error: $_" "WARN"
        return @()
    }
}

function Save-Memory {
    param([string]$Path, [string]$Content)
    try {
        $body = @{ path = $Path; content = $Content } | ConvertTo-Json
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($body)
        $resp = Invoke-RestMethod "$XAVIER2_URL/memory/add" -Method POST -Body $bytes -ContentType "application/json" -Headers @{ "X-Xavier2-Token" = $TOKEN } -TimeoutSec 10
        return $resp.status -eq "ok"
    } catch {
        Write-Log "Memory save error: $_" "WARN"
        return $false
    }
}

function Search-Memory {
    param([string]$Query, [int]$Limit = 3)
    try {
        $body = @{ query = $Query; limit = $Limit } | ConvertTo-Json
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($body)
        $resp = Invoke-RestMethod "$XAVIER2_URL/memory/search" -Method POST -Body $bytes -ContentType "application/json" -Headers @{ "X-Xavier2-Token" = $TOKEN } -TimeoutSec 10
        return $resp
    } catch {
        return $null
    }
}

function Test-Xavier2Health {
    try {
        $resp = Invoke-RestMethod "$XAVIER2_URL/health" -TimeoutSec 5
        return $resp.status -eq "ok"
    } catch {
        return $false
    }
}

function Get-Xavier2Stats {
    try {
        $resp = Invoke-RestMethod "$XAVIER2_URL/memory/stats" -Headers @{ "X-Xavier2-Token" = $TOKEN } -TimeoutSec 5
        return $resp
    } catch {
        return $null
    }
}

function Get-FileStats {
    $srcPath = "E:\scripts-python\xavier2\src"
    if (Test-Path $srcPath) {
        $rustFiles = @(Get-ChildItem $srcPath -Recurse -Filter "*.rs" -ErrorAction SilentlyContinue)
        $totalLines = 0
        foreach ($f in $rustFiles) {
            $totalLines += @(Get-Content $f.FullName -ErrorAction SilentlyContinue).Count
        }
        return @{
            files = $rustFiles.Count
            lines = $totalLines
        }
    }
    return @{ files = 0; lines = 0 }
}

function Create-DevelopmentTask {
    param([object]$Issue)
    
    @"
# Task: #$($Issue.number) - $($Issue.title)

**Created:** $(Get-Date -Format "yyyy-MM-dd HH:mm")
**Source:** $($Issue.html_url)
**Labels:** $($Issue.labels.name -join ", ")

## Problem Statement
$($Issue.body -replace '(?m)^#.*$', '' -replace '(?m)^\-.*$', '' | Select-Object -First 300)

## Directives for this Task

### Think Before Coding
- [ ] What assumptions does this fix make?
- [ ] What could break if we apply this change?
- [ ] Is there a simpler approach?

### Simplicity First
- [ ] Can this be solved with minimal code?
- [ ] What is the smallest valid fix?

### Surgical Changes
- [ ] Which files need to change?
- [ ] Which files should NOT change?

### Goal-Driven
- [ ] How will we verify the fix works?
- [ ] What tests should pass after the fix?

## Files to Examine
$($Issue.body -match '`([^`]+)`' | ForEach-Object { $matches[1] } | Select-Object -Unique | Out-String)

---
*Generated by Xavier2 Development Coordinator v2*
"@
}

function Process-DevelopmentCycle {
    $cycleStart = Get-Date
    $cycleNum = (Get-Content $LOG_FILE -ErrorAction SilentlyContinue | Select-String "Cycle #" | Measure-Object).Count + 1
    
    Write-Log "========================================" "INFO"
    Write-Log "=== Cycle #$cycleNum ===" "INFO"
    
    # 1. Health Check
    $healthy = Test-Xavier2Health
    Write-Log "Xavier2 Health: $(if($healthy){'OK'}else{'DOWN'})" $(if($healthy){'INFO'}else{'ERROR'})
    
    if (-not $healthy) {
        Write-Log "Xavier2 is down. Will retry next cycle." "WARN"
        return $false
    }
    
    # 2. Get Stats
    $stats = Get-Xavier2Stats
    $fileStats = Get-FileStats
    Write-Log "Memory: $($stats.total_memories) memories | Code: $($fileStats.files) .rs files ($($fileStats.lines) LOC)" "INFO"
    
    # 3. Get Issues
    $issues = Get-GitHubIssues
    $p1Issues = $issues | Where-Object { $_.title -match "P0|P1" -or $_.labels.name -contains "P1" }
    $julesIssues = $issues | Where-Object { $_.labels.name -contains "jules" }
    $securityIssues = $issues | Where-Object { $_.title -match "security|test" -or $_.labels.name -contains "security" }
    
    Write-Log "Issues: Open=$($issues.Count) | P1/P0=$($p1Issues.Count) | Jules=$($julesIssues.Count) | Security=$($securityIssues.Count)" "INFO"
    
    # 3b. Get Pull Requests
    $prs = Get-GitHubPRs
    $dependabotPRs = $prs | Where-Object { $_.user.login -match "dependabot" }
    $conflictingPRs = $prs | Where-Object { $_.mergeable -eq "CONFLICTING" }
    $readyPRs = $prs | Where-Object { $_.mergeable -eq "MERGEABLE" }
    
    Write-Log "PRs: Total=$($prs.Count) | Ready=$($readyPRs.Count) | Conflicting=$($conflictingPRs.Count) | Dependabot=$($dependabotPRs.Count)" "INFO"
    
    # 4. Create development tasks for P1 issues
    $tasksCreated = 0
    foreach ($issue in $p1Issues) {
        $existingTask = Search-Memory -Query "task issue-$($issue.number)"
        if ($existingTask.count -eq 0) {
            $taskContent = Create-DevelopmentTask -Issue $issue
            $saved = Save-Memory -Path "projects/xavier2/tasks/issue-$($issue.number)" -Content $taskContent
            if ($saved) {
                Write-Log "Created task for issue #$($issue.number): $($issue.title)" "INFO"
                $tasksCreated++
            }
        }
    }
    
    # 5. Update main status
    $statusContent = @"
# Xavier2 Development Status

**Updated:** $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
**Cycle:** #$cycleNum

## System Health
- Xavier2 Service: $(if($healthy){'✅ Running'}else{'❌ Down'})
- Memory: $($stats.total_memories) memories stored
- Code: $($fileStats.files) Rust files ($($fileStats.lines) lines)

## GitHub Issues Summary
| Category | Count |
|----------|-------|
| Total Open | $($issues.Count) |
| P1/P0 Critical | $($p1Issues.Count) |
| Jules Assigned | $($julesIssues.Count) |
| Security Related | $($securityIssues.Count) |

## Priority Issues (P1/P0)
$(
    if ($p1Issues) {
        $p1Issues | ForEach-Object { "- [#$($_.number)] **$($_.title)**" } | Out-String
    } else {
        "None - all clear!"
    }
)

## Jules Issues
$(
    if ($julesIssues) {
        $julesIssues | ForEach-Object { "- [#$($_.number)] $($_.title)" } | Out-String
    } else {
        "None assigned"
    }
)

## Security Issues
$(
    if ($securityIssues) {
        $securityIssues | ForEach-Object { "- [#$($_.number)] $($_.title)" } | Out-String
    } else {
        "None"
    }
)

## GitHub Pull Requests
| Category | Count |
|----------|-------|
| Total Open | $($prs.Count) |
| Ready to Merge | $($readyPRs.Count) |
| Conflicting | $($conflictingPRs.Count) |
| Dependabot | $($dependabotPRs.Count) |

## Ready PRs (Can Merge)
$(
    if ($readyPRs) {
        $readyPRs | ForEach-Object { "- [#$($_.number)] **$($_.title)** ($($_.user.login))" } | Out-String
    } else {
        "None"
    }
)

## Conflicting PRs (Need Rebase)
$(
    if ($conflictingPRs) {
        $conflictingPRs | ForEach-Object { "- [#$($_.number)] $($_.title)" } | Out-String
    } else {
        "None"
    }
)

## Dependabot PRs (Review Needed)
$(
    if ($dependabotPRs) {
        $dependabotPRs | ForEach-Object { "- [#$($_.number)] $($_.title)" } | Out-String
    } else {
        "None"
    }
)

## Development Tasks Created This Cycle
$tasksCreated tasks generated from P1 issues.

## Agent Directives Applied
1. **Think Before Coding** - Surface assumptions and tradeoffs
2. **Simplicity First** - Minimum viable code
3. **Surgical Changes** - Touch only what's needed
4. **Goal-Driven** - Define success criteria

---
*Xavier2 Development Coordinator v2*
"@
    
    $saved = Save-Memory -Path "projects/xavier2/development/status" -Content $statusContent
    Write-Log "Status saved to Xavier2: $saved" "INFO"
    
    $elapsed = (Get-Date) - $cycleStart
    Write-Log "Cycle completed in $($elapsed.TotalSeconds.ToString('F1'))s" "INFO"
    
    return $true
}

# === MAIN ===
Write-Log "========================================" "INFO"
Write-Log "Xavier2 Development Coordinator v2" "INFO"
Write-Log "Cycle: Every $CycleMinutes minutes" "INFO"
Write-Log "Log: $LOG_FILE" "INFO"
Write-Log "========================================" "INFO"

# Save PID
[System.Diagnostics.Process]::GetCurrentProcess().Id | Out-File $PID_FILE -Force

# Initial cycle
Process-DevelopmentCycle

# Main loop
$cycle = 1
while ($true) {
    Write-Log "Sleeping $($CycleMinutes * 60) seconds until next cycle..." "INFO"
    Start-Sleep -Seconds ($CycleMinutes * 60)
    
    $cycle++
    Process-DevelopmentCycle
}
