use anyhow::Result;
use std::collections::HashMap;
use std::fs;
use std::path::Path;

/// A post generated by Chronicle
pub struct ChroniclePost {
    pub date: String,
    pub title: String,
    pub markdown: String,
    pub metadata: HashMap<String, String>,
}

/// Result of a publication operation
pub struct PublishResult {
    pub success: bool,
    pub destination: String,
    pub url: Option<String>,
}

/// Hook for publishing Chronicle posts to various destinations
pub trait ChroniclePublishHook: Send + Sync {
    /// Returns the unique name of the hook
    fn name(&self) -> &'static str;

    /// Publishes a post to the destination
    fn publish(&self, post: &ChroniclePost) -> Result<PublishResult>;
}

/// Publishes posts to a local directory
pub struct FilePublishHook {
    pub output_dir: String,
}

impl FilePublishHook {
    pub fn new(output_dir: impl Into<String>) -> Self {
        Self {
            output_dir: output_dir.into(),
        }
    }

    fn slugify(&self, title: &str) -> String {
        title
            .to_lowercase()
            .chars()
            .map(|c| if c.is_alphanumeric() { c } else { '-' })
            .collect::<String>()
            .split('-')
            .filter(|s| !s.is_empty())
            .collect::<Vec<_>>()
            .join("-")
    }
}

impl ChroniclePublishHook for FilePublishHook {
    fn name(&self) -> &'static str {
        "file"
    }

    fn publish(&self, post: &ChroniclePost) -> Result<PublishResult> {
        let slug = self.slugify(&post.title);
        let filename = format!("{}-{}.md", post.date, slug);
        let dir_path = Path::new(&self.output_dir);

        if !dir_path.exists() {
            fs::create_dir_all(dir_path)?;
        }

        let file_path = dir_path.join(&filename);

        let mut content = format!("---\ntitle: {}\ndate: {}\n", post.title, post.date);
        for (key, value) in &post.metadata {
            content.push_str(&format!("{}: {}\n", key, value));
        }
        content.push_str("---\n\n");
        content.push_str(&post.markdown);

        fs::write(&file_path, content)?;

        Ok(PublishResult {
            success: true,
            destination: file_path.to_string_lossy().to_string(),
            url: None,
        })
    }
}

/// Publishes posts to standard output (terminal)
pub struct StdoutPublishHook;

impl ChroniclePublishHook for StdoutPublishHook {
    fn name(&self) -> &'static str {
        "stdout"
    }

    fn publish(&self, post: &ChroniclePost) -> Result<PublishResult> {
        println!("--- PUBLISH TO STDOUT ---");
        println!("Title: {}", post.title);
        println!("Date: {}", post.date);
        println!("Metadata: {:?}", post.metadata);
        println!("--- CONTENT ---");
        println!("{}", post.markdown);
        println!("--- END ---");

        Ok(PublishResult {
            success: true,
            destination: "stdout".to_string(),
            url: None,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_file_publish_hook() -> Result<()> {
        let dir = tempdir()?;
        let output_dir = dir.path().to_string_lossy().to_string();
        let hook = FilePublishHook::new(output_dir);

        let mut metadata = HashMap::new();
        metadata.insert("author".to_string(), "Xavier".to_string());

        let post = ChroniclePost {
            date: "2024-05-20".to_string(),
            title: "Test Post".to_string(),
            markdown: "# Hello World\nThis is a test.".to_string(),
            metadata,
        };

        let result = hook.publish(&post)?;

        assert!(result.success);
        assert!(result.destination.contains("2024-05-20-test-post.md"));

        let content = fs::read_to_string(result.destination)?;
        assert!(content.contains("title: Test Post"));
        assert!(content.contains("author: Xavier"));
        assert!(content.contains("# Hello World"));

        Ok(())
    }

    #[test]
    fn test_stdout_publish_hook() -> Result<()> {
        let hook = StdoutPublishHook;
        let post = ChroniclePost {
            date: "2024-05-20".to_string(),
            title: "Test Post".to_string(),
            markdown: "Hello".to_string(),
            metadata: HashMap::new(),
        };

        let result = hook.publish(&post)?;
        assert!(result.success);
        assert_eq!(result.destination, "stdout");

        Ok(())
    }

    #[test]
    fn test_slugify() {
        let hook = FilePublishHook::new(".");
        assert_eq!(hook.slugify("Hello World"), "hello-world");
        assert_eq!(hook.slugify("Hello... World!!!"), "hello-world");
        assert_eq!(hook.slugify("   Spaces   "), "spaces");
    }
}
