use anyhow::{Context, Result};
use pulldown_cmark::{html, Options, Parser};
use std::fs;
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

#[derive(Clone)]
pub struct PostMetadata {
    pub title: String,
    pub date: String,
    pub slug: String,
}

pub struct DevLogSSG {
    input_dir: PathBuf,
    output_dir: PathBuf,
}

const HTML_TEMPLATE: &str = r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}} - Xavier DevLog</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <div class="container">
            <h1><a href="index.html">Xavier DevLog</a></h1>
            <p class="tagline">Cognitive Memory Runtime Technical Logs</p>
        </div>
    </header>
    <main class="container">
        <article>
            {{content}}
        </article>
    </main>
    <footer>
        <div class="container">
            <p>&copy; 2024 Xavier Project. Generated by Xavier SSG.</p>
        </div>
    </footer>
    <script src="main.js"></script>
</body>
</html>"#;

const CSS_ASSET: &str = r#"
:root {
    --bg-color: #0a0a0a;
    --text-color: #e0e0e0;
    --accent-color: #00FF41;
    --header-bg: #121212;
    --border-color: #333;
}

body {
    background-color: var(--bg-color);
    color: var(--text-color);
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    line-height: 1.6;
    margin: 0;
    padding: 0;
}

.container {
    max-width: 800px;
    margin: 0 auto;
    padding: 0 20px;
}

header {
    background-color: var(--header-bg);
    border-bottom: 1px solid var(--accent-color);
    padding: 40px 0;
    margin-bottom: 40px;
}

header h1 {
    margin: 0;
    color: var(--accent-color);
    font-size: 2.5rem;
    text-transform: uppercase;
    letter-spacing: 2px;
}

header h1 a {
    color: inherit;
    text-decoration: none;
}

.tagline {
    margin-top: 10px;
    opacity: 0.8;
}

.post-list {
    list-style: none;
    padding: 0;
}

.post-list li {
    margin-bottom: 15px;
    font-size: 1.2rem;
}

.post-list .date {
    display: inline-block;
    width: 120px;
    font-family: monospace;
    font-size: 0.9rem;
    opacity: 0.7;
}

article {
    background: #111;
    padding: 40px;
    border-radius: 4px;
    border-left: 3px solid var(--accent-color);
}

h1, h2, h3 {
    color: var(--accent-color);
}

a {
    color: var(--accent-color);
}

pre {
    background: #000;
    padding: 15px;
    border-radius: 4px;
    overflow-x: auto;
    border: 1px solid var(--border-color);
}

code {
    font-family: 'Fira Code', 'Courier New', Courier, monospace;
}

footer {
    margin-top: 80px;
    padding: 40px 0;
    border-top: 1px solid var(--border-color);
    text-align: center;
    font-size: 0.9rem;
    opacity: 0.6;
}
"#;

const JS_ASSET: &str = r#"
console.log("Xavier DevLog loaded.");
"#;

impl Default for DevLogSSG {
    fn default() -> Self {
        Self::new()
    }
}

impl DevLogSSG {
    pub fn new() -> Self {
        Self {
            input_dir: PathBuf::from("docs/devlog"),
            output_dir: PathBuf::from("public/devlog"),
        }
    }

    pub fn build(&self) -> Result<()> {
        println!("Building DevLog SSG...");

        if !self.input_dir.exists() {
            fs::create_dir_all(&self.input_dir)?;
            println!("Created input directory: {}", self.input_dir.display());
        }

        if !self.output_dir.exists() {
            fs::create_dir_all(&self.output_dir)?;
            println!("Created output directory: {}", self.output_dir.display());
        }

        // Write assets
        fs::write(self.output_dir.join("style.css"), CSS_ASSET)?;
        fs::write(self.output_dir.join("main.js"), JS_ASSET)?;

        let post_paths = self.discover_posts()?;
        println!("Found {} posts", post_paths.len());

        let mut posts_metadata = Vec::new();

        for path in post_paths {
            let metadata = self.process_post(&path)?;
            posts_metadata.push(metadata);
        }

        self.generate_index(&posts_metadata)?;

        Ok(())
    }

    fn process_post(&self, path: &Path) -> Result<PostMetadata> {
        let content = fs::read_to_string(path)
            .with_context(|| format!("Failed to read post: {}", path.display()))?;

        let filename = path
            .file_stem()
            .expect("test assertion")
            .to_str()
            .expect("test assertion");

        // Simple extraction of title from first # header or filename
        let title = content
            .lines()
            .find(|l| l.starts_with("# "))
            .map(|l| l.trim_start_matches("# ").trim().to_string())
            .unwrap_or_else(|| filename.to_string());

        // Simple extraction of date from filename (expecting YYYY-MM-DD-...)
        let date = if filename.len() >= 10 && &filename[4..5] == "-" && &filename[7..8] == "-" {
            filename[0..10].to_string()
        } else {
            chrono::Utc::now().format("%Y-%m-%d").to_string()
        };

        let html_content = self.render_markdown(&content);

        let full_html = HTML_TEMPLATE
            .replace("{{title}}", &title)
            .replace("{{content}}", &html_content);

        let output_filename = format!("{}.html", filename);
        let output_path = self.output_dir.join(output_filename);

        fs::write(&output_path, full_html)
            .with_context(|| format!("Failed to write HTML: {}", output_path.display()))?;

        Ok(PostMetadata {
            title,
            date,
            slug: format!("{}.html", filename),
        })
    }

    fn generate_index(&self, posts: &[PostMetadata]) -> Result<()> {
        let mut posts_list = String::from("<ul class=\"post-list\">\n");

        // Sort posts by date descending
        let mut sorted_posts = posts.to_vec();
        sorted_posts.sort_by(|a, b| b.date.cmp(&a.date));

        for post in sorted_posts {
            posts_list.push_str(&format!(
                "<li><span class=\"date\">{}</span> <a href=\"{}\">{}</a></li>\n",
                post.date, post.slug, post.title
            ));
        }
        posts_list.push_str("</ul>");

        let index_html = HTML_TEMPLATE.replace("{{title}}", "Home").replace(
            "{{content}}",
            &format!("<h1>Technical Logs</h1>\n{}", posts_list),
        );

        let output_path = self.output_dir.join("index.html");
        fs::write(&output_path, index_html)
            .with_context(|| format!("Failed to write index.html: {}", output_path.display()))?;

        Ok(())
    }

    fn render_markdown(&self, markdown: &str) -> String {
        let mut options = Options::empty();
        options.insert(Options::ENABLE_TABLES);
        options.insert(Options::ENABLE_FOOTNOTES);
        options.insert(Options::ENABLE_STRIKETHROUGH);
        options.insert(Options::ENABLE_TASKLISTS);
        options.insert(Options::ENABLE_HEADING_ATTRIBUTES);

        let parser = Parser::new_ext(markdown, options);
        let mut html_output = String::new();
        html::push_html(&mut html_output, parser);
        html_output
    }

    fn discover_posts(&self) -> Result<Vec<PathBuf>> {
        let mut posts = Vec::new();
        for entry in WalkDir::new(&self.input_dir).max_depth(1) {
            let entry = entry?;
            let path = entry.path();
            if path.is_file() && path.extension().is_some_and(|ext| ext == "md") {
                posts.push(path.to_path_buf());
            }
        }
        posts.sort();
        Ok(posts)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_render_markdown() {
        let ssg = DevLogSSG::new();
        let html = ssg.render_markdown("# Hello\nWorld");
        assert!(html.contains("<h1>Hello</h1>"));
        assert!(html.contains("<p>World</p>"));
    }

    #[test]
    fn test_ssg_build() -> Result<()> {
        let input_dir = tempdir()?;
        let output_dir = tempdir()?;

        let ssg = DevLogSSG {
            input_dir: input_dir.path().to_path_buf(),
            output_dir: output_dir.path().to_path_buf(),
        };

        fs::write(
            input_dir.path().join("2024-05-20-test.md"),
            "# Test\nContent",
        )?;

        ssg.build()?;

        assert!(output_dir.path().join("index.html").exists());
        assert!(output_dir.path().join("2024-05-20-test.html").exists());
        assert!(output_dir.path().join("style.css").exists());
        assert!(output_dir.path().join("main.js").exists());

        let index_content = fs::read_to_string(output_dir.path().join("index.html"))?;
        assert!(index_content.contains("Test"));
        assert!(index_content.contains("2024-05-20"));

        Ok(())
    }
}
